{"hierarchy":{"paths":[["doc:\/\/Afluent\/documentation\/Afluent","doc:\/\/Afluent\/documentation\/Afluent\/AsyncSequences","doc:\/\/Afluent\/documentation\/Afluent\/AsyncSequences\/Completion"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/afluent\/asyncsequences\/completion\/failure(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"failure","kind":"identifier"},{"kind":"text","text":"("},{"text":"Failure","kind":"typeIdentifier"},{"kind":"text","text":")"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/Afluent\/documentation\/Afluent\/AsyncSequences\/Completion\/failure(_:)"},"sections":[],"abstract":[{"type":"text","text":"The sequence completed due to the indicated error."}],"metadata":{"title":"AsyncSequences.Completion.failure(_:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failure"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Failure"},{"text":")","kind":"text"}],"symbolKind":"case","role":"symbol","externalID":"s:7Afluent14AsyncSequencesO10CompletionO7failureyAEy_xGxcAGms5ErrorRzlF","remoteSource":{"url":"https:\/\/github.com\/Tyler-Keith-Thompson\/Afluent\/blob\/main\/Sources\/Afluent\/Subscription\/AnyCancellable.swift#L96","fileName":"AnyCancellable.swift"},"roleHeading":"Case","modules":[{"name":"Afluent"}]},"references":{"doc://Afluent/documentation/Afluent/AsyncSequences/Completion/failure(_:)":{"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"failure","kind":"identifier"},{"kind":"text","text":"("},{"text":"Failure","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/afluent\/asyncsequences\/completion\/failure(_:)","title":"AsyncSequences.Completion.failure(_:)","abstract":[{"text":"The sequence completed due to the indicated error.","type":"text"}],"role":"symbol","identifier":"doc:\/\/Afluent\/documentation\/Afluent\/AsyncSequences\/Completion\/failure(_:)","kind":"symbol"},"doc://Afluent/documentation/Afluent":{"role":"collection","title":"Afluent","abstract":[],"identifier":"doc:\/\/Afluent\/documentation\/Afluent","type":"topic","url":"\/documentation\/afluent","kind":"symbol"},"doc://Afluent/documentation/Afluent/AsyncSequences/Completion":{"identifier":"doc:\/\/Afluent\/documentation\/Afluent\/AsyncSequences\/Completion","abstract":[{"type":"text","text":"A type that represents the completion of a sequence, either due to a normal completion with "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" or an error."}],"role":"symbol","title":"AsyncSequences.Completion","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Completion"}],"navigatorTitle":[{"text":"Completion","kind":"identifier"}],"url":"\/documentation\/afluent\/asyncsequences\/completion"},"doc://Afluent/documentation/Afluent/AsyncSequences":{"url":"\/documentation\/afluent\/asyncsequences","title":"AsyncSequences","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AsyncSequences","kind":"identifier"}],"abstract":[{"text":"A namespace for grouping related AsyncSequence operations.","type":"text"}],"identifier":"doc:\/\/Afluent\/documentation\/Afluent\/AsyncSequences","navigatorTitle":[{"kind":"identifier","text":"AsyncSequences"}]}}}